# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mainservice:
    image: mainservice
    build:
      context: .
      dockerfile: src/main-service/Dockerfile
    ports:
      - 5257:5257
